server:
  port: 8001
  servlet:
    context-path: /bdm-web

spring:
  profiles:
    active: '@profiles.active@'
  application:
    name: bdm-web
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non-null
    time-zone: GMT+8

  #thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/static/pages/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML

  #静态资源本地化读取
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:cn/wangoon/ms/bdm/core/dao/mapping/*.xml,classpath:cn/wangoon/ms/bdm/core/dao/mapping/*/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

test:
  enable: true
  length: 80

#bdm-web系统默认登录账户
bdm-web:
  login:
    domain: http://localhost:8001
    enable: true
    username: admin
    password: admin123456
    urls:
      - /bdm-web/
      - /bdm-web/index/
      - /bdm-web/bases/
      - /bdm-web/tasks/
      - /bdm-web/logs/
      - /bdm-web/bases/pages
      - /bdm-web/tasks/pages
      - /bdm-web/logs/pages

